// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.DTO.DatumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SixteenDaysId")
                        .HasColumnType("int");

                    b.Property<int>("SixteenDaysRootObjectID")
                        .HasColumnType("int");

                    b.Property<double>("app_max_temp")
                        .HasColumnType("float");

                    b.Property<double>("app_min_temp")
                        .HasColumnType("float");

                    b.Property<int>("clouds")
                        .HasColumnType("int");

                    b.Property<int>("clouds_hi")
                        .HasColumnType("int");

                    b.Property<int>("clouds_low")
                        .HasColumnType("int");

                    b.Property<int>("clouds_mid")
                        .HasColumnType("int");

                    b.Property<string>("datetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("dewpt")
                        .HasColumnType("float");

                    b.Property<double>("high_temp")
                        .HasColumnType("float");

                    b.Property<double>("low_temp")
                        .HasColumnType("float");

                    b.Property<string>("max_dhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("max_temp")
                        .HasColumnType("float");

                    b.Property<double>("min_temp")
                        .HasColumnType("float");

                    b.Property<double>("moon_phase")
                        .HasColumnType("float");

                    b.Property<int>("moonrise_ts")
                        .HasColumnType("int");

                    b.Property<int>("moonset_ts")
                        .HasColumnType("int");

                    b.Property<double>("ozone")
                        .HasColumnType("float");

                    b.Property<int>("pop")
                        .HasColumnType("int");

                    b.Property<double>("precip")
                        .HasColumnType("float");

                    b.Property<double>("pres")
                        .HasColumnType("float");

                    b.Property<int>("rh")
                        .HasColumnType("int");

                    b.Property<double>("slp")
                        .HasColumnType("float");

                    b.Property<double>("snow")
                        .HasColumnType("float");

                    b.Property<double>("snow_depth")
                        .HasColumnType("float");

                    b.Property<int>("sunrise_ts")
                        .HasColumnType("int");

                    b.Property<int>("sunset_ts")
                        .HasColumnType("int");

                    b.Property<double>("temp")
                        .HasColumnType("float");

                    b.Property<int>("ts")
                        .HasColumnType("int");

                    b.Property<double>("uv")
                        .HasColumnType("float");

                    b.Property<string>("valid_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("vis")
                        .HasColumnType("float");

                    b.Property<int?>("weatherId")
                        .HasColumnType("int");

                    b.Property<string>("wind_cdir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wind_cdir_full")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wind_dir")
                        .HasColumnType("int");

                    b.Property<double>("wind_gust_spd")
                        .HasColumnType("float");

                    b.Property<double>("wind_spd")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SixteenDaysId");

                    b.HasIndex("weatherId");

                    b.ToTable("Datums");
                });

            modelBuilder.Entity("WebApi.DTO.SixteenDaysRootEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SixteenDaysRootObjects");
                });

            modelBuilder.Entity("WebApi.DTO.WeatherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("WebApi.DTO.DatumEntity", b =>
                {
                    b.HasOne("WebApi.DTO.SixteenDaysRootEntity", "SixteenDays")
                        .WithMany("data")
                        .HasForeignKey("SixteenDaysId");

                    b.HasOne("WebApi.DTO.WeatherEntity", "weather")
                        .WithMany()
                        .HasForeignKey("weatherId");
                });
#pragma warning restore 612, 618
        }
    }
}
